google_analytics_id: UA-48289017-4
copyright: videoadblock.github.io/nowtv
project_name: NOWTV Adblocker
desc: Mit dem NOWTV Adblocker Plugin werden automatisch alle Videos von Werbung oder Adblock Warnungen befreit.